Update WiFiEspClient.cpp
Building nodemcu fails because of .pio\libdeps\nodemcu\WiFiEsp\src\WiFiEspClient.cpp:47:1: error: no return statement in function returning non-void [-Werror=return-type]

Return statement missing.